<div id="tt-pageContent">
    <div class="container-indent nomargin">
        <div class="container-fluid">
            <div class="row">
                <div class="slider-revolution revolution-default">
                    <div class="tp-banner-container">
                        <div class="tp-banner revolution">
                            <ul>
                                <li data-thumb="<?php echo BASE_URL ?>public/images/slides/01/slide-01.jpg" data-transition="fade" data-slotamount="1" data-masterspeed="1000" data-saveperformance="off"  data-title="Slide">
                                    <img src="<?php echo BASE_URL ?>public/images/slides/01/slide-01.jpg"  alt="slide1"  data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" >
                                    <div class="tp-caption tp-caption1 lft stb"
                                        data-x="center"
                                        data-y="center"
                                        data-hoffset="0"
                                        data-voffset="0"
                                        data-speed="600"
                                        data-start="900"
                                        data-easing="Power4.easeOut"
                                        data-endeasing="Power4.easeIn">
                                        <div class="tp-caption1-wd-1 tt-base-color">Los Mejores Productos</div>
                                        <div class="tp-caption1-wd-2">Disfruta<br>De Precios Bajos</div>
                                        <div class="tp-caption1-wd-3">Promociones, Descuentos, Tendencias y Muchos M&acute;s</div>
                                        <div class="tp-caption1-wd-4"><a href="listing-left-column.html" target="_blank" class="btn btn-xl" data-text="SHOP NOW!">COMPRAR YA!</a></div>
                                    </div>
                                </li>
                                <li data-thumb="<?php echo BASE_URL ?>public/images/slides/01/slide-02.jpg" data-transition="fade" data-slotamount="1" data-masterspeed="1000" data-saveperformance="off"  data-title="Slide">
                                    <img src="<?php echo BASE_URL ?>public/images/slides/01/slide-02.jpg"  alt="slide1"  data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" >
                                    <div class="tp-caption tp-caption1 lft stb"
                                        data-x="center"
                                        data-y="center"
                                        data-hoffset="0"
                                        data-voffset="0"
                                        data-speed="600"
                                        data-start="900"
                                        data-easing="Power4.easeOut"
                                        data-endeasing="Power4.easeIn">
                                        <div class="tp-caption1-wd-1 tt-white-color">Calzado</div>
                                        <div class="tp-caption1-wd-2 tt-white-color">Los Mejores<br>Productos</div>
                                        <div class="tp-caption1-wd-3 tt-white-color">Promociones Todos los Dias</div>
                                        <div class="tp-caption1-wd-4"><a href="listing-left-column.html" target="_blank" class="btn btn-xl" data-text="SHOP NOW!">COMPRA YA!</a></div>
                                    </div>
                                </li>
                                <li data-thumb="video/video_img.jpg" data-transition="fade" data-slotamount="1" data-masterspeed="1000" data-saveperformance="off"  data-title="Slide">
                                    <img src="video/blank.png"  alt="slide1"  data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" >
                                    <!-- LAYER NR. 1 -->
                                    <div class="tp-caption tp-fade fadeout fullscreenvideo"
                                        data-x="0"
                                        data-y="0"
                                        data-speed="600"
                                        data-start="0"
                                        data-easing="Power4.easeOut"
                                        data-endspeed="1500"
                                        data-endeasing="Power4.easeIn"
                                        data-autoplay="true"
                                        data-autoplayonlyfirsttime="false"
                                        data-nextslideatend="true"
                                        data-forceCover="1"
                                        data-dottedoverlay="twoxtwo"
                                        data-aspectratio="16:9">
                                        <video class="video-js vjs-default-skin" preload="none"
                                            poster='video/video_img.jpg' data-setup="{}">
                                            <source src='video/video.mp4' type='video/mp4'>
                                        </video>
                                    </div>
                                    <div class="tp-caption  tp-fade"
                                        data-x="right"
                                        data-y="bottom"
                                        data-voffset="-60"
                                        data-hoffset="-90"
                                        data-speed="600"
                                        data-start="900"
                                        data-easing="Power4.easeOut"
                                        data-endeasing="Power4.easeIn">
                                        <div class="video-play">
                                            <a class="icon-f-29 btn-play" href="#"></a>
                                            <a class="icon-f-28 btn-pause" href="#"></a>
                                        </div>
                                    </div>
                                    <!-- TEXT -->
                                    <div class="tp-caption lfb lft text-center"
                                        data-x="center"
                                        data-y="center"
                                        data-voffset="-20"
                                        data-hoffset="0"
                                        data-speed="600"
                                        data-start="900"
                                        data-easing="Power4.easeOut"
                                        data-endeasing="Power4.easeIn">
                                        <div class="tp-caption1-wd-1 tt-base-color">Encuentra</div>
                                        <div class="tp-caption1-wd-2 tt-white-color">Busca Productos<br>Tus Tiendas</div>
                                        <div class="tp-caption1-wd-3 tt-white-color">Aqui encontraras los productos tendencias</div>
                                        <div class="tp-caption1-wd-4"><a href="listing-left-column.html" target="_blank" class="btn btn-xl" data-text="SHOP NOW!">COMPRA YA!</a></div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-indent0">
        <div class="container-fluid">
            <div class="row tt-layout-promo-box">
                <div class="col-sm-12 col-md-6">
                    <div class="row">
                        <div class="col-sm-6">
                            <a href="<?php echo BASE_URL ?>categoria/detalle/1/" class="tt-promo-box tt-one-child hover-type-2">
                                <img src="<?php echo BASE_URL ?>public/images/loader.svg" data-src="<?php echo BASE_URL ?>public/images/promo/index-promo-img-01.jpg" alt="">
                                <div class="tt-description">
                                    <div class="tt-description-wrapper">
                                        <div class="tt-background"></div>
                                        <div class="tt-title-small">EN VENTA</div>
                                    </div>
                                </div>
                            </a>
                            <a href="listing-left-column.html" class="tt-promo-box tt-one-child hover-type-2">
                                <img src="<?php echo BASE_URL ?>public/images/loader.svg" data-src="<?php echo BASE_URL ?>public/images/promo/index-promo-img-02.jpg" alt="">
                                <div class="tt-description">
                                    <div class="tt-description-wrapper">
                                        <div class="tt-background"></div>
                                        <div class="tt-title-small">LO NUEVO</div>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-6">
                            <a href="listing-left-column.html" class="tt-promo-box tt-one-child hover-type-2">
                                <img src="<?php echo BASE_URL ?>public/images/loader.svg" data-src="<?php echo BASE_URL ?>public/images/promo/index-promo-img-03.jpg" alt="">
                                <div class="tt-description">
                                    <div class="tt-description-wrapper">
                                        <div class="tt-background"></div>
                                        <div class="tt-title-small">MUJERES</div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6">
                    <div class="row">
                        <div class="col-sm-6">
                            <a href="listing-left-column.html" class="tt-promo-box tt-one-child hover-type-2">
                                <img src="<?php echo BASE_URL ?>public/images/loader.svg" data-src="<?php echo BASE_URL ?>public/images/promo/index-promo-img-04.jpg" alt="">
                                <div class="tt-description">
                                    <div class="tt-description-wrapper">
                                        <div class="tt-background"></div>
                                        <div class="tt-title-small">HOMBRES</div>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-6">
                            <a href="listing-left-column.html" class="tt-promo-box tt-one-child hover-type-2">
                                <img src="<?php echo BASE_URL ?>public/images/loader.svg" data-src="<?php echo BASE_URL ?>public/images/promo/index-promo-img-05.jpg" alt="">
                                <div class="tt-description">
                                    <div class="tt-description-wrapper">
                                        <div class="tt-background"></div>
                                        <div class="tt-title-small">ACCESORIOS</div>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="col-sm-12">
                            <a href="listing-left-column.html" class="tt-promo-box tt-one-child">
                                <img src="<?php echo BASE_URL ?>public/images/loader.svg" data-src="<?php echo BASE_URL ?>public/images/promo/index-promo-img-06.jpg" alt="">
                                <div class="tt-description">
                                    <div class="tt-description-wrapper">
                                        <div class="tt-background"></div>
                                        <div class="tt-title-small">CALZADO</div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-indent">
        <div class="container container-fluid-custom-mobile-padding">
            <div class="tt-block-title">
                <h1 class="tt-title">TENDENCIAS</h1>
                <div class="tt-description">DE LA SEMANA</div>
            </div>
            <div class="row tt-layout-product-item">
                <?php foreach ($this->productosTendencias as $key => $value) { ?>
                <div class="col-6 col-md-4 col-lg-3">
                    <div class="tt-product thumbprod-center product-nohover">
                        <div class="tt-image-box">
                            <a href="#" class="tt-btn-quickview" data-toggle="modal" data-target="#ModalquickView"  data-tooltip="Vista Rápida" data-tposition="left"></a>
                            <a href="#" class="tt-btn-wishlist" data-tooltip="Añadir a Favorito" data-tposition="left"></a>
                            <a href="#" class="tt-btn-compare" data-tooltip="Añadir a Comparar" data-tposition="left"></a>
                            <a href="<?php echo BASE_URL ?>producto/detalle/<?php echo $value->getId() ?>">
                                <span class="tt-img"><img src="<?php echo BASE_URL ?>public/images/loader.svg" data-src="<?php echo BASE_URL ?>public/img/producto/<?php echo $value->getId() ?>.jpg" alt=""></span>
                                <span class="tt-img-roll-over"><img src="<?php echo BASE_URL ?>public/images/loader.svg" data-src="<?php echo BASE_URL ?>public/img/producto/<?php echo $value->getId() ?>_1.jpg" alt=""></span>
                                <!-- <span class="tt-label-location">
                                    <span class="tt-label-new">New</span>
                                </span> -->
                            </a>
                        </div>
                        <!-- <div class="tt-description">
                            <div class="tt-row">
                                <ul class="tt-add-info">
                                    <li><a href="#">Calificación</a></li>
                                </ul>
                                <div class="tt-rating">
                                    <i class="icon-star"></i>
                                    <i class="icon-star"></i>
                                    <i class="icon-star"></i>
                                    <i class="icon-star-half"></i>
                                    <i class="icon-star-empty"></i>
                                </div>
                            </div>
                            <h2 class="tt-title"><a href="product.html"><?php echo $value->getNombre() ?></a></h2>
                            <div class="tt-price">$<?php echo $value->getPrecio() ?></div>
                            <div class="tt-product-inside-hover">
                                <div class="tt-row-btn">
                                    <a href="#" class="tt-btn-addtocart thumbprod-button-bg" data-toggle="modal" data-target="#modalAddToCartProduct">Añadir al Carrito</a>
                                </div>
                                <div class="tt-row-btn">
                                    <a href="#" class="tt-btn-quickview" data-toggle="modal" data-target="#ModalquickView"></a>
                                    <a href="#" class="tt-btn-wishlist"></a>
                                    <a href="#" class="tt-btn-compare"></a>
                                </div>
                            </div>
                        </div> -->
                    </div>
                </div>
                <?php } ?>
            </div>
        </div>
    </div>
    <div class="container-indent">
        <div class="container-fluid-custom">
            <div class="row tt-layout-promo-box">
                <div class="col-sm-6 col-md-4">
                    <a href="listing-left-column.html" class="tt-promo-box">
                        <img src="<?php echo BASE_URL ?>public/images/loader.svg" data-src="<?php echo BASE_URL ?>public/images/promo/index-promo-img-07.jpg" alt="">
                        <div class="tt-description">
                            <div class="tt-description-wrapper">
                                <div class="tt-background"></div>
                                <div class="tt-title-small">FALL-WINTER CLEARANCE SALES</div>
                                <div class="tt-title-large">GET UP TO <span class="tt-base-color">50% OFF</span></div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-sm-6 col-md-4">
                    <a href="listing-left-column.html" class="tt-promo-box">
                        <img src="<?php echo BASE_URL ?>public/images/loader.svg" data-src="<?php echo BASE_URL ?>public/images/promo/index-promo-img-08.jpg" alt="">
                        <div class="tt-description">
                            <div class="tt-description-wrapper">
                                <div class="tt-background"></div>
                                <div class="tt-title-small">SUMMER <span class="tt-base-color">2018</span></div>
                                <div class="tt-title-large">NEW ARRIVALS</div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-sm-6 col-md-4">
                    <a href="listing-left-column.html" class="tt-promo-box">
                        <img src="<?php echo BASE_URL ?>public/images/loader.svg" data-src="<?php echo BASE_URL ?>public/images/promo/index-promo-img-09.jpg" alt="">
                        <div class="tt-description">
                            <div class="tt-background"></div>
                            <div class="tt-description-wrapper">
                                <div class="tt-background"></div>
                                <div class="tt-title-small">NEW COLLECTION</div>
                                <div class="tt-title-large"><span class="tt-base-color">HANDBAGS</span></div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="container-indent">
        <div class="container container-fluid-custom-mobile-padding">
            <div class="tt-block-title">
                <h2 class="tt-title">LO MAS VENDIDO</h2>
                <div class="tt-description">VENTAS TOP DE LA SEMANA</div>
            </div>
            <div class="row tt-layout-product-item">
                <?php foreach ($this->productosVendidos as $key => $value) { ?>
                <div class="col-6 col-md-4 col-lg-3">
                    <div class="tt-product thumbprod-center product-nohover">
                        <div class="tt-image-box">
                            <a href="#" class="tt-btn-quickview" data-toggle="modal" data-target="#ModalquickView"  data-tooltip="Vista Rápida" data-tposition="left"></a>
                            <a href="#" class="tt-btn-wishlist" data-tooltip="Añadir a Favorito" data-tposition="left"></a>
                            <a href="#" class="tt-btn-compare" data-tooltip="Añadir a Comparar" data-tposition="left"></a>
                            <a href="<?php echo BASE_URL ?>producto/detalle/<?php echo $value->getId() ?>">
                                <span class="tt-img"><img src="<?php echo BASE_URL ?>public/images/loader.svg" data-src="<?php echo BASE_URL ?>public/img/producto/<?php echo $value->getId() ?>.jpg" alt=""></span>
                                <span class="tt-img-roll-over"><img src="<?php echo BASE_URL ?>public/images/loader.svg" data-src="<?php echo BASE_URL ?>public/img/producto/<?php echo $value->getId() ?>_1.jpg" alt=""></span>
                            </a>
                        </div>
                    </div>
                </div>
                <?php } ?>
            </div>
        </div>
    </div>
    <!-- <div class="container-indent">
        <div class="container">
            <div class="tt-block-title">
                <h2 class="tt-title">LATES FROM BLOG</h2>
                <div class="tt-description">THE FRESHEST AND MOST EXCITING NEWS</div>
            </div>
            <div class="tt-blog-thumb-list">
                <div class="row">
                    <div class="col-12 col-sm-6 col-md-6 col-lg-4">
                        <div class="tt-blog-thumb">
                            <div class="tt-img"><a href="blog-single-post.html" target="_blank"><img src="<?php echo BASE_URL ?>public/images/loader.svg" data-src="<?php echo BASE_URL ?>public/images/blog/blog-post-img-06.jpg" alt=""></a></div>
                            <div class="tt-title-description">
                                <div class="tt-background"></div>
                                <div class="tt-tag">
                                    <a href="blog-single-post.html">FASHION</a>
                                </div>
                                <div class="tt-title">
                                    <a href="blog-single-post.html">DOLORE EU FUGIATNULLA PARIATUR</a>
                                </div>
                                <p>
                                    Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                                </p>
                                <div class="tt-meta">
                                    <div class="tt-autor">
                                        by <a href="#">ADRIAN</a> on January 14, 2017
                                    </div>
                                    <div class="tt-comments">
                                        <a href="#"><i class="tt-icon icon-f-88"></i>7</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-md-6 col-lg-4">
                        <div class="tt-blog-thumb">
                            <div class="tt-img"><a href="blog-single-post.html" target="_blank"><img src="<?php echo BASE_URL ?>public/images/loader.svg" data-src="<?php echo BASE_URL ?>public/images/blog/blog-post-img-04.jpg" alt=""></a></div>
                            <div class="tt-title-description">
                                <div class="tt-background"></div>
                                <div class="tt-tag">
                                    <a href="blog-single-post.html">FASHION</a>
                                </div>
                                <div class="tt-title">
                                    <a href="blog-single-post.html">INCIDIDUNT UT LABORE ET DOLORE</a>
                                </div>
                                <p>
                                    Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                                </p>
                                <div class="tt-meta">
                                    <div class="tt-autor">
                                        by <a href="#">ADRIAN</a> on January 14, 2017
                                    </div>
                                    <div class="tt-comments">
                                        <a href="#"><i class="tt-icon icon-f-88"></i>7</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-md-6 col-lg-4">
                        <div class="tt-blog-thumb">
                            <div class="tt-img"><a href="blog-single-post.html" target="_blank"><img src="<?php echo BASE_URL ?>public/images/loader.svg" data-src="<?php echo BASE_URL ?>public/images/blog/blog-post-img-02.jpg" alt=""></a></div>
                            <div class="tt-title-description">
                                <div class="tt-background"></div>
                                <div class="tt-tag">
                                    <a href="blog-single-post.html">FASHION</a>
                                </div>
                                <div class="tt-title">
                                    <a href="blog-single-post.html">INCIDIDUNT UT LABORE ET DOLORE</a>
                                </div>
                                <p>
                                    Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                                </p>
                                <div class="tt-meta">
                                    <div class="tt-autor">
                                        by <a href="#">ADRIAN</a> on January 14, 2017
                                    </div>
                                    <div class="tt-comments">
                                        <a href="#"><i class="tt-icon icon-f-88"></i>7</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> -->
    <div class="container-indent">
        <div class="container-fluid">
            <div class="tt-block-title">
                <h2 class="tt-title"><a target="_blank" href="https://www.instagram.com/wokieeshop/">@ FOLLOW</a> US ON</h2>
                <div class="tt-description">INSTAGRAM</div>
            </div>
            <div class="row">
                <div id="instafeed" class="instafeed-fluid"
                    data-accessToken="8626857013.dd09515.0fcd8351c65140d48f5a340693af1c3f"
                    data-clientId="dd095157744c4bd0a67181fc4906e5b6"
                    data-userId="8626857013"
                    data-limitImg="6">
                </div>
            </div>
        </div>
    </div>
    <div class="container-indent">
        <div class="container">
            <div class="row tt-services-listing">
                <div class="col-xs-12 col-md-6 col-lg-4">
                    <a href="#" class="tt-services-block">
                        <div class="tt-col-icon">
                            <i class="icon-f-48"></i>
                        </div>
                        <div class="tt-col-description">
                            <h4 class="tt-title">FREE SHIPPING</h4>
                            <p>Free shipping on all US order or order above $99</p>
                        </div>
                    </a>
                </div>
                <div class="col-xs-12 col-md-6 col-lg-4">
                    <a href="#" class="tt-services-block">
                        <div class="tt-col-icon">
                            <i class="icon-f-35"></i>
                        </div>
                        <div class="tt-col-description">
                            <h4 class="tt-title">SUPPORT 24/7</h4>
                            <p>Contact us 24 hours a day, 7 days a week</p>
                        </div>
                    </a>
                </div>
                <div class="col-xs-12 col-md-6 col-lg-4">
                    <a href="#" class="tt-services-block">
                        <div class="tt-col-icon">
                            <i class="icon-e-09"></i>
                        </div>
                        <div class="tt-col-description">
                            <h4 class="tt-title">30 DAYS RETURN</h4>
                            <p>Simply return it within 24 days for an exchange.</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>