<div class="col-md-6 col-md-offset-3" > 
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Cambiar</h3>
		</div>
		<div class="panel-body">
			<form role="form" method="post" action="<?php echo BASE_URL; ?>login/cambiar/" >
				<fieldset>
					<div class="form-group">
						<input  class="form-control required" placeholder="Contraseña Actual" maxlength="30" name="passAct" type="password" autocomplete="off" value="">
					</div>
					<div class="form-group">
						<input  class="form-control required" placeholder="Contraseña Nueva" maxlength="30" name="passNue" type="password" autocomplete="off" value="">
					</div>
					<div class="form-group">
						<input  class="form-control required" placeholder="Repetir Contraseña" maxlength="30" name="passRep" type="password" autocomplete="off" value="">
					</div>
					<div class="form-group">
					</div>
					<input type="submit" class="btn btn-primary btn-block" value="Cambiar" />
				</fieldset>
			</form>
		</div>
	</div>
</div>

