<div class="col-md-6 col-md-offset-3" > 
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Iniciar Sesión</h3>
		</div>
		<div class="panel-body">
			<form role="form" method="post" action="<?php echo BASE_URL; ?>login/" >
				<fieldset>
					<div class="form-group">
						<input class="form-control required" placeholder="Usuario" name="usuario" autocomplete="off"  autofocus>
					</div>
					<div class="form-group">
						<input  class="form-control required" placeholder="Contraseña"  name="pass" type="password" autocomplete="off" value="">
					</div>

					<div class="form-group">
					</div>
					<input type="submit" class="btn btn-primary btn-block" value="Acceder" />
				</fieldset>
			</form>
		</div>
	</div>
</div>

