<div class="tt-breadcrumb">
    <div class="container">
        <ul>
            <li><a href="<?php echo BASE_URL ?>">Inicio</a></li>
            <?php foreach ($this->miga as $key => $value) { ?>
                <li><a href="<?php echo BASE_URL.$value['url'] ?>"><?php echo $value['nombre'] ?></a></li>
            <?php } ?>
        </ul>
    </div>
</div>
<div id="tt-pageContent">
	<div class="container-indent">
		<div class="container">
			<h1 class="tt-title-subpages noborder">YA TE ENCUENTRAS REGISTRADO ?</h1>
			<div class="tt-login-form">
				<div class="row">
					<div class="col-xs-12 col-md-6">
						<div class="tt-item">
							<h2 class="tt-title">NUEVO CLIENTE</h2>
							<p>
								Al crear una cuenta en nuestra tienda, podrá moverse a través del proceso de pago más rápido, almacenar múltiples direcciones de envío, ver y rastrear sus pedidos en su cuenta y más.
							</p>
							<div class="form-group">
								<a href="<?php echo BASE_URL ?>registro/" class="btn btn-top btn-border">CREAR UNA CUENTA</a>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-md-6">
						<div class="tt-item">
							<h2 class="tt-title">INICIAR SESION</h2>
							Si tiene una cuenta con nosotros, por favor Iniciar Sesión.
							<div class="form-default form-top">
								<form id="formLogin" method="post" novalidate="novalidate">
									<div class="form-group">
										<label>USUARIO O CORREO *</label>
										<div class="tt-required">* Campos Requeridos</div>
										<input type="text" name="email" class="form-control" placeholder="Ingrese usuario o correo">
									</div>
									<div class="form-group">
										<label>CLAVE *</label>
										<input type="text" name="clave" class="form-control" placeholder="Ingrese clave">
									</div>
									<div class="row">
										<div class="col-auto mr-auto">
											<div class="form-group">
												<button class="btn btn-border" type="submit">INICIAR SESION</button>
											</div>
										</div>
										<div class="col-auto align-self-end">
											<div class="form-group">
												<ul class="additional-links">
													<li><a href="#">Olvidastes tu Clave ?</a></li>
												</ul>
											</div>
										</div>
									</div>

								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

