<div class="tt-breadcrumb">
    <div class="container">
        <ul>
            <li><a href="index.html">Home</a></li>
            <li>Create An Account</li>
        </ul>
    </div>
</div>
<div id="tt-pageContent">
    <div class="container-indent">
        <div class="container">
            <h1 class="tt-title-subpages noborder">CREAR UNA CUENTA</h1>
            <div class="tt-login-form">
                <div class="row justify-content-center">
                    <div class="col-md-8 col-lg-6">
                        <div class="tt-item">
                            <h2 class="tt-title">INFORMACION PERSONAL</h2>
                            <div class="form-default">
                                <form id="formRegistro" method="post" novalidate="novalidate">
                                    <div class="form-group">
                                        <label>NOMBRE *</label>
                                        <div class="tt-required">* Campos Requeridos</div>
                                        <input type="text" name="nombre" class="form-control" placeholder="Ingrese el nombre">
                                    </div>
                                    <div class="form-group">
                                        <label>CELULAR *</label>
                                        <input type="text" name="celular" class="form-control" placeholder="Ingrese el celular">
                                    </div>
                                    <div class="form-group">
                                        <label>E-MAIL *</label>
                                        <input type="text" name="email" class="form-control" placeholder="Ingrese el e-mail">
                                    </div>
                                    <div class="form-group">
                                        <label>CLAVE *</label>
                                        <input type="text" name="clave" class="form-control" placeholder="Ingrese la clave">
                                    </div>
                                    <div class="row">
                                        <div class="col-auto">
                                            <div class="form-group">
                                                <button class="btn btn-border" type="submit">CREAR CUENTA</button>
                                            </div>
                                        </div>
                                        <div class="col-auto align-self-center">
                                            <div class="form-group">
                                                <ul class="additional-links">
                                                    <li>or <a href="#">Regresar</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>