<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dosificacion extends \Entities\Dosificacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'dosis', 'fechainicio', 'plantilla', 'estado', 'cantidadmensajes', 'mensajesenviados', 'tipomensaje', 'recompra', 'frecuencia', 'medicamento', 'cliente', 'usuario');
        }

        return array('__isInitialized__', 'id', 'dosis', 'fechainicio', 'plantilla', 'estado', 'cantidadmensajes', 'mensajesenviados', 'tipomensaje', 'recompra', 'frecuencia', 'medicamento', 'cliente', 'usuario');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Dosificacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDosis($dosis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDosis', array($dosis));

        return parent::setDosis($dosis);
    }

    /**
     * {@inheritDoc}
     */
    public function getDosis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDosis', array());

        return parent::getDosis();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechainicio($fechainicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechainicio', array($fechainicio));

        return parent::setFechainicio($fechainicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechainicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechainicio', array());

        return parent::getFechainicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlantilla($plantilla)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlantilla', array($plantilla));

        return parent::setPlantilla($plantilla);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlantilla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlantilla', array());

        return parent::getPlantilla();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadmensajes($cantidadmensajes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadmensajes', array($cantidadmensajes));

        return parent::setCantidadmensajes($cantidadmensajes);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadmensajes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadmensajes', array());

        return parent::getCantidadmensajes();
    }

    /**
     * {@inheritDoc}
     */
    public function setMensajesenviados($mensajesenviados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMensajesenviados', array($mensajesenviados));

        return parent::setMensajesenviados($mensajesenviados);
    }

    /**
     * {@inheritDoc}
     */
    public function getMensajesenviados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMensajesenviados', array());

        return parent::getMensajesenviados();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipomensaje($tipomensaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipomensaje', array($tipomensaje));

        return parent::setTipomensaje($tipomensaje);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipomensaje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipomensaje', array());

        return parent::getTipomensaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecompra($recompra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecompra', array($recompra));

        return parent::setRecompra($recompra);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecompra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecompra', array());

        return parent::getRecompra();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrecuencia($frecuencia = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrecuencia', array($frecuencia));

        return parent::setFrecuencia($frecuencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrecuencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrecuencia', array());

        return parent::getFrecuencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedicamento($medicamento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedicamento', array($medicamento));

        return parent::setMedicamento($medicamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedicamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedicamento', array());

        return parent::getMedicamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente($cliente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', array($cliente));

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', array());

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

}
